import { db } from './firebase';
import { collection, addDoc, getDocs, query, where, serverTimestamp, updateDoc, doc } from 'firebase/firestore';
import { logger } from './logger';

export interface CampaignMetrics {
  sent: number;
  opened: number;
  replied: number;
  converted: number;
}

export interface MarketingCampaign {
  id?: string;
  businessId: string;
  title: string;
  objective: 'reactivation' | 'fill_slots' | 'upsell' | 'loyalty';
  targetAudience: string;
  targetClientIds: string[];
  messageTemplate: string;
  status: 'draft' | 'approved' | 'running' | 'completed' | 'paused';
  metrics: CampaignMetrics;
  isAutoGenerated: boolean;
  sendAt?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

/**
 * Função simulada do Motor de Automação de Marketing (Módulos 1-4).
 * Identifica públicos-alvo como inativos e sugere mensagens contextuais.
 */
export const generateMarketingOpportunities = async (businessId: string) => {
  logger.info(`Starting AI Marketing analysis for business: ${businessId}`);
  
  try {
    const clientsRef = collection(db, 'clients');
    const qClients = query(clientsRef, where('business_id', '==', businessId));
    const clientsSnap = await getDocs(qClients);
    
    const now = new Date();
    const inactiveClients: { id: string, name: string }[] = [];
    const recurringClients: { id: string, name: string }[] = [];

    // Módulo 1 & 2: Identificação Oportunidades Baseado em Tempo/Retenção
    clientsSnap.forEach(doc => {
        const c = doc.data();
        const lastVisitDate = c.last_appointment_date || c.last_visit;
        if (lastVisitDate) {
            const lastVisit = lastVisitDate.toDate ? lastVisitDate.toDate() : new Date(lastVisitDate);
            const diffDays = Math.floor((now.getTime() - lastVisit.getTime()) / (1000 * 3600 * 24));
            
            if (diffDays > 30 && diffDays < 90) { // Inativos (mais de 30 dias)
                inactiveClients.push({ id: doc.id, name: c.name });
            } else if (diffDays <= 30 && (c.appointments_count || c.total_visits || 0) > 3) { // Recorrentes, aptos a Upsell
                recurringClients.push({ id: doc.id, name: c.name });
            }
        }
    });

    // Módulo 3 & 4: Geração de Campanhas Baseado no Público
    
    // 1. Campanha de Reativação
    if (inactiveClients.length > 0) {
        const campaign: MarketingCampaign = {
            businessId,
            title: 'Recuperação de Inativos (+30 dias)',
            objective: 'reactivation',
            targetAudience: `Clientes Inativos Padrão (${inactiveClients.length} pessoas)`,
            targetClientIds: inactiveClients.map(c => c.id),
            messageTemplate: `Oi {{primeiro_nome}}, sumiu hein? 😅 Faz um tempo desde seu último serviço. Liberamos um horário especial amanhã. Que tal agendar?`,
            status: 'draft',
            metrics: { sent: 0, opened: 0, replied: 0, converted: 0 },
            isAutoGenerated: true,
        };
        await saveCampaignIfUnique(campaign);
    }

    // 2. Campanha de Upsell / Retenção
    if (recurringClients.length > 5) {
        const campaign: MarketingCampaign = {
            businessId,
            title: 'Oferta Exclusiva: Clientes VIP',
            objective: 'upsell',
            targetAudience: `Clientes Recorrentes Frequentes (${recurringClients.length} pessoas)`,
            targetClientIds: recurringClients.map(c => c.id),
            messageTemplate: `E aí {{primeiro_nome}}, tudo bom? Notamos que você é cliente frequente! Adicione o serviço X no seu próximo agendamento com um super desconto. ✨`,
            status: 'draft',
            metrics: { sent: 0, opened: 0, replied: 0, converted: 0 },
            isAutoGenerated: true,
        };
        await saveCampaignIfUnique(campaign);
    }

    // INTEGRAÇÃO: Sistema de Fidelidade
    const qsLoyalty = query(collection(db, 'loyalty_balances'), where("business_id", "==", businessId));
    const loyaltySnap = await getDocs(qsLoyalty).catch(() => null);
    const loyaltyClientsIds: string[] = [];
    if (loyaltySnap && !loyaltySnap.empty) {
        loyaltySnap.forEach(doc => {
            const data = doc.data();
            if (data.balance >= 50 && data.client_id) {
                loyaltyClientsIds.push(data.client_id);
            }
        });
    }

    if (loyaltyClientsIds.length > 0) {
        const campaign: MarketingCampaign = {
            businessId,
            title: 'Resgate de Pontos de Fidelidade',
            objective: 'loyalty',
            targetAudience: `Clientes com saldo para resgate (${loyaltyClientsIds.length} pessoas)`,
            targetClientIds: loyaltyClientsIds,
            messageTemplate: `Olá {{primeiro_nome}}! 🎁 Você tem pontos acumulados no nosso Sistema de Fidelidade esperando por você! Troque hoje mesmo por serviços grátis ou descontos. Agende agora!`,
            status: 'draft',
            metrics: { sent: 0, opened: 0, replied: 0, converted: 0 },
            isAutoGenerated: true,
        };
        await saveCampaignIfUnique(campaign);
    }

    // INTEGRAÇÃO: Sistema de Agendamento (Preencher Horários Vazios)
    const startOfTomorrow = new Date();
    startOfTomorrow.setDate(startOfTomorrow.getDate() + 1);
    const tomorrowStr = startOfTomorrow.toISOString().split('T')[0];

    const qAppts = query(collection(db, 'appointments'), where('business_id', '==', businessId), where('date', '==', tomorrowStr));
    const apptsSnap = await getDocs(qAppts).catch(() => null);
    
    // Se a agenda estiver com poucos agendamentos (menor que 5, para simplificar)
    if (apptsSnap && apptsSnap.size < 5 && recurringClients.length > 0) {
        const campaign: MarketingCampaign = {
            businessId,
            title: 'Oferta Relâmpago: Preencher Agenda de Amanhã',
            objective: 'fill_slots',
            targetAudience: `Clientes Frequentes (${recurringClients.length} pessoas)`,
            targetClientIds: recurringClients.map(c => c.id),
            messageTemplate: `Ei {{primeiro_nome}}! Tivemos desistências para amanhã e liberamos um horário com desconto especial se você agendar agora. Topa? 🚀`,
            status: 'draft',
            metrics: { sent: 0, opened: 0, replied: 0, converted: 0 },
            isAutoGenerated: true,
        };
        await saveCampaignIfUnique(campaign);
    }

    logger.info(`AI Marketing generation complete for ${businessId}`);
  } catch (error) {
     logger.error('Error running AI Marketing Generation', error, { businessId });
  }
};

async function saveCampaignIfUnique(campaign: MarketingCampaign) {
    const q = query(
        collection(db, 'marketing_campaigns'),
        where('businessId', '==', campaign.businessId),
        where('title', '==', campaign.title),
        where('status', '==', 'draft')
    );
    const snap = await getDocs(q);
    if (snap.empty) {
        await addDoc(collection(db, 'marketing_campaigns'), {
            ...campaign,
            createdAt: serverTimestamp(),
            updatedAt: serverTimestamp()
        });
        logger.info(`New AI Marketing Campaign created: ${campaign.title}`);
    }
}

/**
 * Simula a execução da campanha disparando mensagens via integração no WhatsApp (Módulo 5)
 */
export const executeCampaign = async (businessId: string, campaignId: string, clientIdsCount: number) => {
    try {
        // Obter configuração de limite
        const qCfg = query(collection(db, "marketing_configs"), where("businessId", "==", businessId));
        const cfgSnap = await getDocs(qCfg);
        let dailyLimit = 100;
        let daysBetween = 7;
        
        if (!cfgSnap.empty) {
            const data = cfgSnap.docs[0].data();
            dailyLimit = data.dailySendLimit || 100;
            daysBetween = data.daysBetweenCampaigns || 7;
        }

        const ref = doc(db, 'marketing_campaigns', campaignId);
        await updateDoc(ref, {
            status: 'running',
            updatedAt: serverTimestamp()
        });
        
        logger.info(`Campaign ${campaignId} execution started via WhatsApp Worker. Limits -> Daily: ${dailyLimit}, Cooldown: ${daysBetween} days`);
        
        // Simular o sistema em background que atualizaria de 'running' para 'completed' com as métricas preenchidas
        setTimeout(async () => {
             // Limita a quantidade de envios ao dailyLimit configurado (Anti-Spam Módulo 8)
             const actualSends = Math.min(clientIdsCount, dailyLimit);

             const simulatedOpened = Math.floor(actualSends * 0.7);
             const simulatedConverted = Math.floor(actualSends * 0.2);

             await updateDoc(ref, {
                 status: 'completed',
                 metrics: {
                     sent: actualSends,
                     opened: simulatedOpened,
                     replied: Math.floor(actualSends * 0.3),
                     converted: simulatedConverted
                 },
                 updatedAt: serverTimestamp()
             });
        }, 3000);

        return true;
    } catch (e) {
        logger.error(`Error executing campaign ${campaignId}`, e);
        return false;
    }
};

export const approveCampaign = async (campaignId: string) => {
    try {
        const ref = doc(db, 'marketing_campaigns', campaignId);
        await updateDoc(ref, {
            status: 'approved',
            updatedAt: serverTimestamp()
        });
        return true;
    } catch (e) {
        return false;
    }
};
