export const PRESET_THEMES = [
  {
    id: "flowza-official",
    name: "Flowza Official",
    emoji: "⚡",
    desc: "O tema padrão da Flowza — escuro, minimalista e focado em conversão",
    primary_color: "#7c3aed", secondary_color: "#1a1a2e", accent_color: "#d4a853",
    background_color: "#0c0c14", text_color: "#FFFFFF",
    font_body: "Inter", font_heading: "Inter",
    border_radius: "large", layout_style: "modern",
  },
  {
    id: "dark-luxury",
    name: "Dark Luxury",
    emoji: "🖤",
    desc: "Escuro, elegante e sofisticado",
    primary_color: "#D4A853", secondary_color: "#1A1A2E", accent_color: "#C9A84C",
    background_color: "#0F0F23", text_color: "#FFFFFF",
    font_body: "DM Sans", font_heading: "Playfair Display",
    border_radius: "rounded", layout_style: "classic",
  },
  {
    id: "clean-white",
    name: "Clean White",
    emoji: "⚪",
    desc: "Branco, limpo e minimalista",
    primary_color: "#111111", secondary_color: "#F5F5F5", accent_color: "#2563EB",
    background_color: "#FFFFFF", text_color: "#111111",
    font_body: "Inter", font_heading: "Space Grotesk",
    border_radius: "rounded", layout_style: "minimal",
  },
  {
    id: "vintage",
    name: "Vintage",
    emoji: "🪵",
    desc: "Clássico, rústico e acolhedor",
    primary_color: "#8B4513", secondary_color: "#F5E6D3", accent_color: "#CD853F",
    background_color: "#FFF8F0", text_color: "#3E2723",
    font_body: "Crimson Text", font_heading: "Libre Baskerville",
    border_radius: "small", layout_style: "classic",
  },
  {
    id: "neon",
    name: "Neon",
    emoji: "💜",
    desc: "Vibrante, futurista e impactante",
    primary_color: "#A855F7", secondary_color: "#1E1B4B", accent_color: "#06B6D4",
    background_color: "#0A0A1A", text_color: "#E0E7FF",
    font_body: "Sora", font_heading: "Outfit",
    border_radius: "large", layout_style: "bold",
  },
  {
    id: "tropical",
    name: "Tropical",
    emoji: "🌴",
    desc: "Colorido, alegre e descontraído",
    primary_color: "#059669", secondary_color: "#ECFDF5", accent_color: "#F59E0B",
    background_color: "#F0FDF4", text_color: "#064E3B",
    font_body: "Nunito", font_heading: "Montserrat",
    border_radius: "full", layout_style: "modern",
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    emoji: "🌊",
    desc: "Azul profundo e profissional",
    primary_color: "#3B82F6", secondary_color: "#1E293B", accent_color: "#38BDF8",
    background_color: "#0F172A", text_color: "#F1F5F9",
    font_body: "Work Sans", font_heading: "Raleway",
    border_radius: "rounded", layout_style: "modern",
  },
  {
    id: "rose-gold",
    name: "Rosé Gold",
    emoji: "🌸",
    desc: "Delicado, feminino e elegante",
    primary_color: "#BE185D", secondary_color: "#FFF1F2", accent_color: "#D4A574",
    background_color: "#FFF5F7", text_color: "#4A1D34",
    font_body: "Lato", font_heading: "Playfair Display",
    border_radius: "large", layout_style: "classic",
  },
];
